# Generated by Django 5.2.17 on 2026-09-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('PRESS_RELEASE', 'Press release'), ('CIRCULAR', 'Circular'), ('POLICY', 'Policy or regulation'), ('PUBLIC_NOTICE', 'Public notice'), ('FAQ', 'Frequently asked question'), ('REPORT', 'Report'), ('OFFICIAL_STATEMENT', 'Official statement'), ('OTHER', 'Other official material')], default='OTHER', max_length=40)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('file_reference', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_content_type', models.CharField(blank=True, max_length=120)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('SUPERSEDED', 'Superseded')], default='PENDING_REVIEW', max_length=30)),
                ('published', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=True)),
                ('extraction_status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('MANUAL_TEXT', 'Manual text supplied'), ('PENDING', 'Extraction pending'), ('AVAILABLE', 'Text available'), ('FAILED', 'Extraction failed')], default='NOT_STARTED', max_length=30)),
                ('indexing_status', models.CharField(choices=[('NOT_INDEXED', 'Not indexed'), ('PENDING', 'Indexing pending'), ('READY', 'Ready for retrieval'), ('FAILED', 'Indexing failed')], default='NOT_INDEXED', max_length=30)),
                ('source_priority', models.PositiveSmallIntegerField(default=100)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to='institutions.officialuser')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_documents', to='institutions.governmentinstitution')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_documents', to='institutions.officialuser')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='documents.officialdocument')),
            ],
            options={
                'ordering': ['-publication_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published', 'is_current'], name='documents_o_status_4de89d_idx'), models.Index(fields=['institution', 'status'], name='documents_o_institu_90613d_idx')],
            },
        ),
    ]
