# Generated by Django 5.2.17 on 2026-09-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('QUEUED', 'Queued for extraction'), ('PROCESSING', 'Extraction in progress'), ('COMPLETED', 'Extraction completed'), ('FAILED', 'Extraction failed'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled')], default='PENDING_REVIEW', max_length=30)),
                ('processing_status', models.CharField(choices=[('NOT_CONFIGURED', 'No extraction worker configured'), ('PENDING', 'Pending extraction'), ('RUNNING', 'Extraction in progress'), ('COMPLETED', 'Extraction completed'), ('FAILED', 'Extraction failed')], default='NOT_CONFIGURED', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_sources', to='institutions.governmentinstitution')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_sources', to='institutions.officialuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'processing_status'], name='documents_k_status_a56420_idx'), models.Index(fields=['institution', 'created_at'], name='documents_k_institu_eabcbd_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'url'), name='documents_knowledge_source_institution_url_uniq')],
            },
        ),
    ]
