from __future__ import annotations

from django.db.models import Q
from django.utils import timezone

from apps.documents.models import OfficialDocument, OfficialDocumentStatus
from apps.institutions.models import InstitutionVerificationStatus

from .ai import generate_grounded_answer, provider_status


def _public_documents():
    today = timezone.localdate()
    return (
        OfficialDocument.objects.select_related("institution")
        .filter(
            status=OfficialDocumentStatus.APPROVED,
            published=True,
            is_current=True,
            institution__active=True,
            institution__verification_status=InstitutionVerificationStatus.VERIFIED,
        )
        .filter(Q(expiry_date__isnull=True) | Q(expiry_date__gte=today))
        .filter(Q(effective_date__isnull=True) | Q(effective_date__lte=today))
    )


def search_approved_official_content(query, limit=5):
    query = query.strip()
    if not query:
        return []

    documents = (
        _public_documents()
        .filter(
            Q(title__icontains=query)
            | Q(description__icontains=query)
            | Q(body_text__icontains=query)
        )
        .order_by("-publication_date", "-created_at")[:limit]
    )
    return [
        {
            "id": document.id,
            "title": document.title,
            "institution": document.institution.name,
            "institution_acronym": document.institution.acronym,
            "category": document.category,
            "document_type": document.document_type,
            "source_url": document.source_url or None,
            "publication_date": document.publication_date,
            "effective_date": document.effective_date,
            "expiry_date": document.expiry_date,
            "excerpt": document.body_text[:600],
            "verification_status": "approved_official",
        }
        for document in documents
    ]


def answer_from_approved_sources(query, language="auto"):
    """Return a cautious answer grounded in approved, currently valid records.

    The database lookup is always performed first. If the optional Hugging Face
    layer is enabled and available, it may phrase an answer in the requested
    language using only the returned excerpts. A model failure or missing
    configuration falls back to the deterministic lookup; it never fabricates
    evidence or a verification verdict.
    """
    evidence = search_approved_official_content(query)
    generated = generate_grounded_answer(
        query=query,
        evidence=evidence,
        language=language,
    )

    if evidence:
        strength = "moderate" if len(evidence) > 1 else "limited"
        status = "evidence_found"
        fallback_answer = (
            "I found approved official material that may help verify this question. "
            "Read the cited source and its dates before treating it as current."
        )
    else:
        strength = "none"
        status = "not_verified"
        fallback_answer = (
            "I could not verify this claim from the approved official sources currently "
            "available. Check the original institution source or wait for a reviewed record."
        )

    if generated and generated.text:
        answer = generated.text
        ai_generated = True
        # The provider is only called when at least one approved excerpt matched,
        # so generated wording is always grounded in returned evidence.
        ai_status = "grounded"
        limitations = (
            "This response was generated by the configured language model using only the "
            "approved-source excerpts shown. It may be incomplete or wrong and is not a "
            "final verification or fraud judgment. Review the linked source."
        )
    else:
        answer = fallback_answer
        ai_generated = False
        if not evidence and provider_status() == "ready":
            ai_status = "not_needed"
        else:
            ai_status = generated.status if generated else provider_status()
        limitations = (
            "This lookup does not treat citizen reports as facts and does not make a "
            "political judgment. It is not a substitute for reviewing the linked source."
        )

    return {
        "status": status,
        "answer": answer,
        "evidence_strength": strength,
        "evidence": evidence,
        "ai_generated": ai_generated,
        "ai_status": ai_status,
        "language": language,
        "limitations": limitations,
    }
