# Generated by Django 5.2.17 on 2026-09-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('official_domain', models.CharField(blank=True, max_length=255)),
                ('official_email_domain', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('GOVERNMENT_MINISTRY', 'Government ministry'), ('GOVERNMENT_DEPARTMENT', 'Government department'), ('GOVERNMENT_AGENCY', 'Government agency'), ('POLICE', 'Police'), ('REGULATOR', 'Regulator'), ('PUBLIC_INSTITUTION', 'Public institution'), ('LOCAL_GOVERNMENT', 'Local government'), ('PUBLIC_HEALTH', 'Public health'), ('EDUCATION', 'Education'), ('FINANCE', 'Finance'), ('AGRICULTURE', 'Agriculture'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('PUBLIC_SAFETY', 'Public safety'), ('OTHER', 'Other verified organization')], default='OTHER', max_length=40)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfficialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appwrite_user_id', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('GOVERNMENT_OFFICIAL', 'Government official'), ('ORGANIZATION_OFFICIAL', 'Organization official'), ('CONTENT_EDITOR', 'Content editor'), ('VERIFICATION_OFFICER', 'Verification officer'), ('ANALYST', 'Analyst'), ('ADMIN', 'Administrator'), ('SUPER_ADMIN', 'Super administrator')], default='ANALYST', max_length=40)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_accounts', to='institutions.officialuser')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='official_users', to='institutions.governmentinstitution')),
            ],
            options={
                'ordering': ['institution__name', 'email'],
            },
        ),
    ]
