# Generated by Django 5.2.17 on 2026-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=32, unique=True)),
                ('claim', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='OTHER', max_length=80)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('evidence_file_id', models.CharField(blank=True, max_length=255)),
                ('evidence_name', models.CharField(blank=True, max_length=255)),
                ('evidence_content_type', models.CharField(blank=True, max_length=120)),
                ('evidence_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('evidence_processing_status', models.CharField(choices=[('NOT_PROVIDED', 'No evidence provided'), ('PENDING', 'Evidence pending'), ('STORED', 'Evidence stored privately'), ('REJECTED', 'Evidence rejected'), ('FAILED', 'Evidence processing failed')], default='NOT_PROVIDED', max_length=30)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under review'), ('ACTION_TAKEN', 'Action taken'), ('CLOSED', 'Closed')], default='RECEIVED', max_length=30)),
                ('appwrite_sync_status', models.CharField(choices=[('NOT_CONFIGURED', 'Not configured'), ('PENDING', 'Pending synchronization'), ('SYNCED', 'Synchronized'), ('FAILED', 'Synchronization failed')], default='NOT_CONFIGURED', max_length=30)),
                ('google_sheets_sync_status', models.CharField(choices=[('NOT_CONFIGURED', 'Not configured'), ('PENDING', 'Pending synchronization'), ('SYNCED', 'Synchronized'), ('FAILED', 'Synchronization failed')], default='NOT_CONFIGURED', max_length=30)),
                ('appwrite_document_id', models.CharField(blank=True, max_length=255)),
                ('submitted_channel', models.CharField(default='public_web', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_fra_status_e79c5d_idx'), models.Index(fields=['category', 'created_at'], name='reports_fra_categor_4245d8_idx')],
            },
        ),
    ]
